/********************************************/
///POR FAVOR NO BORRAR NADA

#ifndef MISION_H_INCLUDED
#define MISION_H_INCLUDED

///EN EL CASO DE QUE EN LA ESTRUCTURA HAYA UN TIPO DE DATO DE OTRA ESTRUCTURA, USAR #INCLUDE ..NOMBRE ESTRUCTURA...
///HEADER DE ASTRONAUTA , AQUI SE PONEN LAS CABECERAS DE ASTRONAUTA.

/*
    AQUI PONDREMOS:
    |-> ESTRUCTURAS
    |-> ENCABEZADOS DE NUESTRAS FUNCIONES DE ASTRONAUTA (NO VAN LAS FUNCIONES ACA).
*/


/********************************************/





///POR FAVOR NO BORRAR NADA
#endif // MISION_H_INCLUDED
